### ISSUE TITLE
possibilité of costume validation

### ISSUE THREAD

**Issue by soufiane0123** [Michelphoenix98/flutter_survey#2]
all question have same message

![image](https://user-images.githubusercontent.com/111284741/198233417-1f8b70b5-2c23-4c95-947e-67d257c99b52.png)

**Comment by Michelphoenix98** [comment]
Hi, 
At present you can set it using the builder method and passing your own custom widget or using the existing QuestionCard widget and setting the validator field. Are you suggesting that we include a field called a field called errorText in the json objects passed to the Survey widget?

**Comment by soufiane0123** [comment]
yeah! just add errorText field

**Comment by Michelphoenix98** [comment]
Added a parameter to the Question model. I will be closing this issue now.
