### ISSUE TITLE
problem in question of type textField

### ISSUE THREAD

**Issue by soufiane0123** [Michelphoenix98/flutter_survey#3]
survey didn't read the input of textField

![image](https://user-images.githubusercontent.com/111284741/198246280-4c875071-4fbc-43be-8156-cec049d46f75.png)

**Comment by Michelphoenix98** [comment]
Ah yes, it's been set to onSubmit. I'll need to change it onChanged. Thanks
for pointing it out! I'll roll out a fix for all the issue by
midnight tonight.

**Comment by soufiane0123** [comment]
@Michelphoenix98 good package. Keep up with good work!!

**Comment by Michelphoenix98** [comment]
Fixed the issue, I've released an update for the same. I will be closing this issue for now. Thank you for raising the issue!
